name: 'dbt_learn_proj'
version: '2.0.0'

profile: 'dbt_learn_proj'

clean-targets:
  - "target"

model-paths: ["models"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ['seeds']



models:
  dbt_learn_proj:
    silver_airbnb:
      +schema: 'silver_airbnb'
      +materialized: view

    gold_airbnb:
      +schema: 'gold_airbnb'
      +materialized: table

