dbt_learn_proj:
  outputs:
    dev:
      account: HLPFGQD-ZO88945
      database: DEV
      password: Anviksha@12345
      role: TRANSFORM
      schema: bronze_airbnb
      threads: 1
      type: snowflake
      user: ankur24s
      warehouse: COMPUTE_WH
  target: dev
